### ISSUE TITLE
Allow projects to have a default activity

### ISSUE THREAD

**Issue by Kennric** [osuosl/timesync-node#106]
Add a default activity to projects, such that an admin can specify what activity time will be associated with if time entries do not provide an activity.

This requires allowing null activity fields in time entry submissions, and allowing a default activity to be defined on project creation (and edited as needed).

If no default is set for a project, then there are a couple of options: 
1. a default is assigned (requires at least one activity to be created at time of project creation)
2. a default activity is created (project specific?) and assigned on project creation
3. the default is left null, and time entry submissions are then required to provide an activity (more complex logic)

**Comment by iankronquist** [comment]
I got a little bit of this done but ran out of time. I don't think I will be able to work on it between now and the all-hands, but I don't want the work to go to waste either.
https://github.com/osuosl/timesync-node/commit/d52d459043e074720672e3c80998ca780e42d6f7
