### ISSUE TITLE
times fixtures should store ``created_at`` and ``date_worked`` as iso dates

### ISSUE THREAD

**Issue by ElijahCaine** [osuosl/timesync-node#109]
``created_at`` and ``date_worked`` are currently set to null in the tests. Since those will never be null in production their fixtures should be set to a dummy date (I am going with 2015-04-15). This will require a few tests to be updated.

**Comment by tschuy** [comment]
Have you made any progress on getting this implemented?

**Comment by tschuy** [comment]
Fixed in #133
