### ISSUE TITLE
Extend the testing infrastructure to allow for smaller testing scope

### ISSUE THREAD

**Issue by ElijahCaine** [osuosl/timesync-node#112]
This addition would allow the developer to only run specific tests in the suite. This option is actually very easy to implement as mocha already has an option for this:

```
-g, --grep <pattern>                    only run tests matching <pattern>
```

Essentially the user can pass the -g option to a mocha call and only run tests that have that string in the description (``mocha -g POST`` would only run POST related tests for instance).

The way our infrastructure is currently setup we can't just run ``npm test -g POST``, it throws the following error:

```
$ npm test -g POST                                                           

> timesync@0.0.0 test /path/to/timesync-node
> DATABASE=mocha PORT=8851 DEBUG=true mocha --harmony tests "POST"

/path/to/timesync-node/node_modules/mocha/lib/utils.js:591
      if (!files.length) throw new Error("cannot resolve path (or pattern) '" 
                               ^
Error: cannot resolve path (or pattern) 'POST'
    at Object.lookupFiles (/path/to/timesync-node/node_modules/mocha/lib/utils.js:591:32)
    at /path/to/timesync-node/node_modules/mocha/bin/_mocha:320:30
    at Array.forEach (native)
    at Object.<anonymous> (/path/to/timesync-node/node_modules/mocha/bin/_mocha:319:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Test failed.  See above for more details.
```

The solution is a simple bash script, so if anybody wants some experience with bash, this is the issue for you.

We can discuss what should and should not be allowed to be test scoped. The ``linter`` command could be scoped so it only lints files that match a substring, but commands like ``coverage`` and ``latte`` are only really useful if they test *everything*.

Honestly I'm just tired of waiting for a bunch of tests to complete when I only care about the X that I'm writing right now.

**Comment by tschuy** [comment]
``tschuy@diamond:(timesync)(elijah/post-projects) → npm test -- -g POST``

**Comment by ElijahCaine** [comment]
Well egg on my face.
