### ISSUE TITLE
[Web] Design library

### ISSUE THREAD

**Issue by tschuy** [osuosl/timesync-node#15]
https://medium.com/google-developers/introducing-material-design-lite-3ce67098c031

I'm personally in favor of using a design library like this one to create the web interface. <3 material design. Thoughts?

We also currently don't have a timesync web repository. We might want to create one.

**Comment by iankronquist** [comment]
Have you used this library at all? Is it easy to use or will you spend your whole time fighting it?

Material design is popular these days. I wonder how well it will age.  I can think of a javascript web frameworks whose glossy ui has not kept up with the times.

On the whole this sounds like a good idea, and material design is fairly lightweight and pretty.

**Comment by tschuy** [comment]
I'm planning on using this for a personal project this week, so I'll be
able to report how much pain it has (at least the surface of it) hopefully.

Also, personal site redesign incoming :D :D :D

**Comment by LyonesGamer** [comment]
If I could drop in a suggestion, I'm rather partial to Bootstrap. But I'm definitely willing to look into look into MDL if you come back with positive thoughts.

**Comment by lucywyman** [comment]
I haven't used MDL before, but it seems easy to use and effective for what we want.  I'm in favor of using it (particularly over bootstrap, sorry @LyonesGamer).  Are we still interested in a web interface repository @Kennric?  I understand if it's not high priority, but saw this issue and want to know where we stand on it.

**Comment by LyonesGamer** [comment]
Front-end development is occurring in separate repos as we no longer wish to confine timesync to a single client.
