### ISSUE TITLE
Use transactions

### ISSUE THREAD

**Issue by tschuy** [osuosl/timesync-node#153]
c'est bon pour la santé!

Right now if we suffer a bug, something that makes something throw, etc., our data is happily saved into some random incomplete state.

Using transactions would save us from this HORRIBLE, HORRIBLE fate.

**Comment by tschuy** [comment]
Handy dandy docs http://knexjs.org/#Transactions

**Comment by LyonesGamer** [comment]
This has been solved by #191 and #192.
