### ISSUE TITLE
[5] Soft Delete Times + Activities + Projects & Update Select Statements & Hard Delete Slugs

### ISSUE THREAD

**Issue by ElijahCaine** [osuosl/timesync-node#173]
Update database statements to soft delete everything except slugs (to avoid slug conflict down the road).

**Soft Deleted:**
- Activities
- Projects
- Times

**Hard Deleted:**
- Project slugs

**Comment by LyonesGamer** [comment]
From previous issue #163:

Before a project can be deleted, the following must be true:

the user deleting the project must have admin rights
slugs associated with the project must be deleted
userroles associated with the project must be deleted

**Comment by ElijahCaine** [comment]
This has been closed in favor of three individual issues: #186 #187 and #188
