### ISSUE TITLE
Upgrade to Node 4.2.0

### ISSUE THREAD

**Issue by tschuy** [osuosl/timesync-node#195]
Hooray, the LTS release is out!

https://nodejs.org/en/blog/release/v4.2.0/

We should upgrade to this. I'll work on getting it deployed to our workstations.

**Comment by LyonesGamer** [comment]
Once it's deployed, do you expect it to require any significant code changes?

**Comment by LyonesGamer** [comment]
Workstations have all been upgraded to v4.2.2 LTS, required no changes to timesync. We currently make no recommendations about version, so I can close this.
