### ISSUE TITLE
[13] Add "include_deleted" parameter

### ISSUE THREAD

**Issue by ElijahCaine** [osuosl/timesync-node#197]
This parameter will include deleted objects in any list of objects to a query, or just a deleted object if you reuqest a specific one (instead of returning a 404).

**Comment by athai** [comment]
The issue was split up into three sections to be more manageable.

* Activities: 7 hours 56 minutes, status: [complete]
* Projects: 3 hours 1 minute, status: [in progress]
* Times: N/A

**Comment by athai** [comment]
Resolved by #212.
