### ISSUE TITLE
[8] Implement ?user= query parameter

### ISSUE THREAD

**Issue by tschuy** [osuosl/timesync-node#24]
For the ``/times`` endpoint, we want to be able to query for times from certain users.

By saying ``?user=tschuy``, we want only times that I've submitted. By saying ``?user=patcht&user=tschuy``, we want to get the union of times for me and @LyonesGamer.

If the ?activity or ?activity parameters are implemented before this, make sure that both of those work with this.

There's also no documentation as of yet for this parameter.

**Comment by LyonesGamer** [comment]
Superseded by #130
