### ISSUE TITLE
Implement ?activity= query parameter

### ISSUE THREAD

**Issue by tschuy** [osuosl/timesync-node#25]
For the ``/times`` endpoint, we want to be able to query for times from certain activities.

By saying ``?activity=meetings``, we want only times spent in meetings. By saying ``?activity=meetings&activity=planning``, we want to get the union of times spent in meetings and planning.

If the ?user or ?project parameters are implemented before this, make sure that both of those work with this.

There's also no documentation as of yet for this parameter.

**Comment by LyonesGamer** [comment]
Superseded by #122
