### ISSUE TITLE
Implement ?project= query parameter

### ISSUE THREAD

**Issue by tschuy** [osuosl/timesync-node#26]
For the ``/times`` endpoint, we want to be able to query for times from certain projects.

By saying ``?project=gwm``, we want only times spent working on Ganeti Web Manager. By saying ``?project=gwm&project=wf``, we want to get the union of times spent on GWM and What's Fresh.

If the ?user or ?activity parameters are implemented before this, make sure that both of those work with this.

There's also no documentation as of yet for this parameter.

**Comment by LyonesGamer** [comment]
Superseded by #127
