### ISSUE TITLE
Garbage characters being sent when requesting token

### ISSUE THREAD

**Issue by aaroncohen73** [osuosl/timesync-node#269]
Description:
The base64 encoded JSON data that is returned by the server when a token is requested is sometimes appended with garbage unprintable characters. This causes timesync-frontend-flask to raise an error when trying to parse the token.

If the token is blindly passed back to the server, the server accepts it just fine. The problem just occurs when the client tries to parse the token. For this reason, if you go to `http://timesync-staging.osuosl.org/v0/times?token=<insert token here>` the server will respond normally.

For some reason, this doesn't happen with every user. Tokens for the `test` user don't contain these garbage characters. I'm pretty sure that this isn't an issue with Pymesync since I remember the `admin` account working properly since the last time Pymesync was updated.

Steps to replicate:
1) Clone timesync-frontend-flask
2) Follow the directions in the README to copy config.py.dist to config.py and set DEBUG to True
3) Run the app
4) Go to http://localhost:5000/login and log in as `admin` with the password `timesync-staging`

**Comment by ElijahCaine** [comment]
When you run a curl command to get an auth token it works fine, and requests with that auth token work fine as well. The only problem is when we base64 decode the token we get garbage after the expected JSON object output.

**Comment by tschuy** [comment]
Why would anything be base64 decoding the token?

**Comment by matthewrsj** [comment]
@aaroncohen73 why is timesync-frontend-flask parsing the token? Shouldn't that all be handled by Pymesync? Or do you mean it causes Pymesync to raise an error?

@tschuy Pymesync parses the token so it can calculate the expiration time of the token and tell the frontend when it needs to re-auth.

**Comment by aaroncohen73** [comment]
@matthewrsj The error is raised inside Pymesync when it tries to read the token inside token_expiration_time.

**Comment by matthewrsj** [comment]
@aaroncohen73 interesting. Do you have an example token that causes an error? Share it on IRC if you do please.

**Comment by LyonesGamer** [comment]
This was determined to be a bug in PymeSync's processing of tokens. The third section of a JWT token is a base64-encoded HMAC-encrypted signature; if you decode that section, it will appear to be garbage characters. Unfortunately, PymeSync did not always split the signature from the payload section.
