### ISSUE TITLE
Endpoints should only return objects which users have permission to read

### ISSUE THREAD

**Issue by ElijahCaine** [osuosl/timesync-node#277]
After a quick check of the tests I don't believe we enforce this.

When a user requests something like `GET /projects` they should only get back times they have permission to see.

**Comment by LyonesGamer** [comment]
Could you be more specific? As it is, we limit times to only the times a user can see (when they do ``GET /times``), but we agreed that users, projects, and activities shouldn't be limited. When a user performs ``GET /projects``, they receive all projects. Is that not what we're testing for?

**Comment by LyonesGamer** [comment]
I'm not even sure that could even work for activities. There's nothing that ties activities to users.

**Comment by Kennric** [comment]
I think projects and activities should probably be visible to all, I just want to verify and make sure this is documented, as this behavior strongly influences how we design a front end (getting all projects and iterating over them to find a user's membership vs just getting projects).

**Comment by LyonesGamer** [comment]
I do feel that our API documentation is fairly clear that ``GET /projects`` and ``GET /activities`` will return all available objects (we state that ``GET /${type}`` endpoints will return ALL objects, and specifically call out ``GET /times`` as being *different* in returning only *some* times), but if you want I probably could see if I could clarify it more.

I definitely agree that we could do either ``GET /projects?user=...`` or ``GET /user/.../projects`` to only return a certain user's projects though. That also has the benefit that e.g. a manager can see what projects another user is on as well.
