### ISSUE TITLE
Typo in knexfile.js

### ISSUE THREAD

**Issue by aaroncohen73** [osuosl/timesync-node#298]
Under the "production_sqlite" environment in `knexfile.js`, `client: 'sqite3'` should be `client: 'sqlite3'`

**Comment by tschuy** [comment]
Interestingly, the commit responsible for that typo is "Minor typo": https://github.com/osuosl/timesync-node/commit/fe76a1da66a0e5a063d616583f83cbd0f6459b49

**Comment by aaroncohen73** [comment]
That's an accurate commit message as it is, indeed, a minor typo

**Comment by LyonesGamer** [comment]
@tschuy: Yeah, I just wanted to leave it unclear whether I was fixing a minor typo or introducing one. Clearly.
