### ISSUE TITLE
Connection to TimeSync failed at baseurl http://timesync.osuosl.org/v0 - response status was 503

### ISSUE THREAD

**Issue by ElijahCaine** [osuosl/timesync-node#308]
Using the pymesync library in climesync I get a 503 response after doing just a small number of transactions in a single activity.  Let's figure out why.

**Comment by LyonesGamer** [comment]
I am so far unable to reproduce it. Could you see if you're still experiencing this today?

**Comment by ElijahCaine** [comment]
@LyonesGamer Unfortunately no, but I'm going to keep this issue around in case we do replicate it.

**Comment by LyonesGamer** [comment]
This error has not been seen in some time. If it occurs again, we'll make a new issue. As-is, it appears to be fixed.
