### ISSUE TITLE
errorAuthenticationTypeFailure not formatting errors properly

### ISSUE THREAD

**Issue by aaroncohen73** [osuosl/timesync-node#309]
Instead of creating an error with a type and a text, `errorAuthenticationTypeFailure` provides the error text as the error type. As a result, no error text is sent back in the JSON object when frontends might be expecting error text. According to the comments in `errors.js`, this should be a `Bad Query Value` error.

**Comment by LyonesGamer** [comment]
This was fixed by #310.
