### ISSUE TITLE
POST /times endpoint

### ISSUE THREAD

**Issue by tschuy** [osuosl/timesync-node#33]
To add a new object, POST to */times/* with a JSON body:

    {
      "duration":12,
      "user": <username>,
      "project": <slug>,
      "activity": <slug>,
      "notes":"",
      "issue_uri":"https://github.com/osu-cass/whats-fresh-api/issues/56",
      "date_worked":null,
      "created_at":null,
      "updated_at":null
    }

**Comment by LyonesGamer** [comment]
Superseded by issues #55, #56, #57, #58, and #59.
