### ISSUE TITLE
DELETE endpoints

### ISSUE THREAD

**Issue by tschuy** [osuosl/timesync-node#35]
A DELETE request sent to any object's endpoint will result in a DELETE of the
object. For instance, DELETE-ing /activities/1 will return a 200 and delete the
object.

The response body upon success will be empty.

Upon an error, it will return an Object Not Found error with a 404 status code.

    {
        error: "Object not found",
        errno: 1,
        text: "Invalid activity"
    }

As this is a fairly simple endpoint, I think this should be alright being a single issue.

**Comment by LyonesGamer** [comment]
Should we be sending it to /activities/:id or /activities/:slug?

**Comment by LyonesGamer** [comment]
Barring that question, I have the tests for this one done, but I want to wait for PR #12 to be merged so that the PR for this isn't behind.

**Comment by iankronquist** [comment]
#12 was merged. Are the tests hanging out in a branch somewhere?

**Comment by LyonesGamer** [comment]
No, they're just saved locally in my branch. I wanted to rebase before
pushing the tests, especially since it would probably affect my tests.

**Comment by LyonesGamer** [comment]
Superseded by #101 and #93
