### ISSUE TITLE
OSL should adopt a code of conduct

### ISSUE THREAD

**Issue by iankronquist** [osuosl/timesync-node#53]
GitHub [recently adopted](https://github.com/blog/2039-adopting-the-open-code-of-conduct) a code of conduct for their major projects. I think we should follow their bold lead and adopt a code of conduct for TimeSync. [Here](http://todogroup.org/opencodeofconduct/#Atom/opensource@github.com) is the one they use for atom. I would be willing to investigate alternatives. I am open to reasoned discussion, but let's keep it professional, unlike some places on the internet.

I believe the lab's projects should accept contributions from anyone and we should affirm our commitment to support those who are sidelined or even discriminated against in the world of open source. This includes allowing anyone to publicly express their identity and share their ideas in a workplace appropriate manner.

**Comment by ElijahCaine** [comment]
@iankronquist I don't quiet understand why this is necessary for TimeSync. Could you elaborate why TimeSync in particular should have a code of conduct?

If we had a problem with contribution I would agree with you but PR and Issue discussions seem to be pretty tame from my point of view.

**Comment by Kennric** [comment]
@ElijahCaine - basically, a CoC is something every project should have, in the same way it has docs on crontributing, etc. Really, we should have an org-wide one that all projects conform to. There are a lot of reasons to be pro-active about codes of conduct, and we should have a longer org-wide discussion about it. In summary:

* CoC advertises a commitment to a welcoming environment which promotes project participation
* CoC makes is clear what behavior is expected and what the remedies are - if something bad ever does happen, there is no ambiguity about what was acceptable and what to do about it
* CoC would help many open source projects and the reputation of FOSS in general, we should lead by example

**Comment by ElijahCaine** [comment]
@Kennric I agree with the fact that we should have an org-wide Code of Conduct. My confusion stemmed mostly from why *TimeSync* needed a CoC in particular. I would like to move toward the OSL having a CoC for it's projects.

**Comment by iankronquist** [comment]
Sorry for not replying to this one. I think @kennric's points are all good. I tossed this out there because talk of codes of conduct is in the air and the OSL doesn't have one. TimeSync moves a lot faster than most other OSL projects so I figured I could open issue here, provoke some discussion, and not have the conversation fester like it might if I opened it against some other repos.

**Comment by LyonesGamer** [comment]
An organization-wide Code of Conduct is currently in progress and will be released when complete. This issue is no longer relevant.
