### ISSUE TITLE
Check URI Helper Function

### ISSUE THREAD

**Issue by ElijahCaine** [osuosl/timesync-node#58]

**Comment by tschuy** [comment]
Looks like there's an npm module that does everything we were going to do, but ... better: https://www.npmjs.com/package/valid-url

Should I write a helper function still? It'd literally just be a wrapper for validUrl.isWebUri().

**Comment by tschuy** [comment]
valid-url works as so, returning the string (which is true-y if it's not null) if it's a valid string:

```
> var validUrl = require('valid-url');
undefined
> validUrl.isWebUri('http://test.com')
'http://test.com'
> validUrl.isWebUri('http://test.com/')
'http://test.com/'
> validUrl.isWebUri('ftp://test.com/')
undefined
> validUrl.isWebUri('https://test.com/')
'https://test.com/'
```

**Comment by ElijahCaine** [comment]
@tschuy 
**Pros of wrapper function**: if we decide to do any other checking in addition to isWebUri's functionality it's easy to add. What kind of other checking? Good question, I'm not sure.
**Cons of wrapper function**: It's more code to manage that might break.
**Either way** we need to test the Check URI functionality.

Thoughts?

**Comment by tschuy** [comment]
I think no wrapper function for now. It'll be easy to add in the future if we really want add'l checking, and for now I don't see a reason we'd want add'l checking.

**Comment by tschuy** [comment]
I'd be open to input from anyone else, @matthewrsj @athai @Kennric

**Comment by matthewrsj** [comment]
I agree this is enough. I don't think we need a wrapper function.

**Comment by Kennric** [comment]
I agree, a wrapper function is more than we need, lets not solve problems we don't have yet.
