### ISSUE TITLE
create isAuthenticated functionality

### ISSUE THREAD

**Issue by ElijahCaine** [osuosl/timesync-node#61]
Check that the password matches and the user is active.

**Comment by tschuy** [comment]
Depends on #61.

**Comment by tschuy** [comment]
I've started work in https://github.com/osuosl/timesync-node/tree/tschuy/add_passport. It's rough so far but it's coming along nicely.

**Comment by tschuy** [comment]
Docs for reference: http://passportjs.org/docs/authenticate

**Comment by tschuy** [comment]
Fixed by #74
